### ISSUE TITLE
Please implement travis-ci support

### ISSUE THREAD

**Issue by danmarsden** [pwsdb/moodle-block_remaining_lesson_timer#5]
Some of the tests run by the Moodle.org plugins db can be run via travis-ci on each commit in your github repo. Making your code comply with the moodle coding guidelines also makes it much easier for the review team to review your code.
More information on this is here:
https://moodle.org/mod/forum/discuss.php?d=323384

but the short version:
grab this file:
https://github.com/moodlerooms/moodle-plugin-ci/blob/master/.travis.dist.yml
rename it as .travis.yml and put in the root of your github directory.
Go to:
https://travis-ci.org/pwsdb
Flick the switch for this repo.

then on every commit you make to github it will fire off a request to travis to run the tests in .travis.yml and will give you traffic lights beside each commit and generate a report.

something else you might want to change:
in .travis.yml the default file has this line:

env:
global:

MOODLE_BRANCH=MOODLE_32_STABLE
you might want to add other branches to that list (or remove 32_STABLE because it's not supported.) so you might want to change it something like:

env:
global:

MOODLE_BRANCH=MOODLE_33_STABLE
MOODLE_BRANCH=MOODLE_34_STABLE
MOODLE_BRANCH=MOODLE_35_STABLE

**Comment by pwsdb** [comment]
I have re-submitted the latest commit to  https://moodle.org/plugins/block_remaining_lesson_timer  
and the updated moodle coding guidelines report can be seen there. . . . 
Thank you.

**Comment by danmarsden** [comment]
is there a reason you have decided not to implement travis support here in github?

**Comment by danmarsden** [comment]
Hi Greg, 
travis-ci runs behat and unit tests as well as a bunch of other things on your code for every commit in github. It also runs them when someone submits a pull request so you can see if things pass before you merge the code into your main release.

Firefox is mentioned in the travis config because the BEHAT tests that travis runs on Moodle requires a certain version of Firefox to run smoothly. (just leave it there.)

here's an example of a pull request that was made to one of my plugins and failed on it's first run:
https://travis-ci.org/danmarsden/moodle-mod_attendance/builds/425001464

There are a few different ways to add new files to your github repo - aftern you have created the file locally typically you would use git - something like:
git add .travis.yml
git commit -a     (and then add a useful message to the commit)
git push origin master

But - Github also lets you add and edit files from within the web interface if you really want to - if you go here:
https://github.com/pwsdb/moodle-block_remaining_lesson_timer beside the green button "clone" you'll see an "add file" button - give the file the name .travis.yml and then copy the text of the .travis.dist.yml file into this new file and save.
If you have enabled travis-ci already it should automatically trigger a new build.

hope that helps!

**Comment by pwsdb** [comment]
Thanks

**Comment by pwsdb** [comment]
I did not see a switch.  "Flick the switch for this repo."  I saw the page where it says "there are no builds for this repo" and clicked on my lesson-tmer "repo" and thought I was "Flicking" it, but I don't know.

**Comment by danmarsden** [comment]
looks like it's set up - although I'm seeing weird travis errors on some of my builds today too - so you might want to leave it for a bit and check again tomorrow.

**Comment by pwsdb** [comment]
It has been 2 days, does it work for you? how do I try it?  I saw where it found an unused variable. nice.  I deleted the variable.

**Comment by danmarsden** [comment]
yeah - looks like you've got it sorted! - nice! :-)
